config/routes.rb
Rails.application.routes.draw do
  post 'auth/login', to: 'authentication#login'
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  devise_for :users
  root "users#index"
  resources :users, only: [:index, :show]   do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      get '/page/:page', action: :index, on: :collection
      resources :likes, only: [:create], path: ""
      resources :likes, only: [:destroy], path: ""
      resources :comments, only: [:create, :destroy], path: "comment"
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_comments_counter
  after_destroy :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApiController
  include ActionController::HttpAuthentication::Token::ControllerMethods

  def current_user
    authenticate_with_http_token do |token, _options|
      User.find(JsonWebToken.decode(token)[:user_id])
    end
  end

  def index
    @comments = Post.find(params[:post_id]).comments
    render json: @comments
  end

  def create
    @comment = Post.find(params[:post_id]).comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(params.require(:comment).permit(:text))
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to request.referrer
    else
      redirect_to request.referrer
      flash[:warning] = 'Comment cannot be empty!'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:success] = 'Comment deleted'
    else
      flash[:warning] = 'Comment cannot be deleted'
    end
    redirect_to request.referrer
  end
end

app/views/comments/_comment.html.erb
<ul class="card ms-3 me-3 mt-1 p-3">
  <% comments.each do |comment| %>
    <li class= 'd-flex justify-content-between mb-3'>
      <div>
        <span class="p1"><%= comment.user.name %>: </span>
        <span class="p1"><%= comment.text %></span>
      </div>
      <% if comment.user_id == current_user.id || can?(:destroy, current_user) %>
        <%= button_to "Delete", user_post_comment_path(comment.user_id, comment.post_id, comment.id), method: :delete, class: "btn btn-outline-secondary" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/comments/_create.html.erb
<section class="create-comments m-3">
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      <div class="new-comment-form">
        <%= form_with url: "/users/#{params[:user_id]}/posts/#{params[:id]}/comment", method: :post, data: { turbo: true } do |form| %>
          <div>
            <br>
            <%= form.label :text, hidden: true %>
            <%= form.text_area :text, name: "comment[text]", cols: 50, placeholder: "Add a new comment", class: "form-control" %> <br>
          </div>
          <div>
            <button class="btn btn-outline-secondary" type="submit" name="commit" value="Comment">Comment</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>