config/routes.rb
Rails.application.routes.draw do
  post 'auth/login', to: 'authentication#login'
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  devise_for :users
  root "users#index"
  resources :users, only: [:index, :show]   do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      get '/page/:page', action: :index, on: :collection
      resources :likes, only: [:create], path: ""
      resources :likes, only: [:destroy], path: ""
      resources :comments, only: [:create, :destroy], path: "comment"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :posts, dependent: :destroy, foreign_key: :author_id
  has_many :comments, dependent: :destroy, foreign_key: :user_id
  has_many :likes, dependent: :destroy, foreign_key: :user_id

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  # Define roles
  enum role: { user: 'user', admin: 'admin' }

  # Ability rules for CancanCan
  def ability
    @ability ||= Ability.new(self)
  end

  delegate :can?, :cannot?, to: :ability

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  def index
    @users = User.all
    render json: @users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<div class="row m-3">
  <div style="width: 10rem;" class="col-3 d-flex ps-0">
        <%= image_tag(user.photo, class: "img-fluid") %>
  </div>
  <div class="col card mt-2 mb-2">
    <div class="row g-0">
      <div class="">
        <div class="card-body">
          <h2 class="card-title fs-1 mt-3"><%= user.name %></h2>
          <p class="card-text text-end fs-5"><small class="text-body-secondary">Number of posts: <%= user.posts_counter %></small></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user_path(user) do %>
        <%= render partial: "user", locals: { user: user } %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= link_to users_path do %>
  <%= render partial: "user", locals: { user: User.find(params[:id]) } %>
<% end %>

<section class="card m-3">
  <div class="card-body">
    <h5 class="card-title">Bio</h5>
    <p class="card-text"><%= @user.bio %></p>
  </div>
</section>

<% if current_user == @user %>
  <div class="d-flex ms-3 me-3">
    <%= link_to "Add New Post", new_user_post_path(@user), class: "col btn btn-outline-secondary"%>
  </div>
<% end %>

<ul>
  <% @user.three_most_recent_posts.each_with_index do |post , i| %>
    <li>
      <%= render partial: "posts/post", locals: { post: post, i: i } %>
    </li>
  <% end %>
</ul>

<div class="text-center m-3 mb-4">
  <%= link_to "See all posts", user_posts_path(@user), class: "btn btn-outline-secondary p-2"%>
</div>