config/routes.rb
Rails.application.routes.draw do
  post 'auth/login', to: 'authentication#login'
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  devise_for :users
  root "users#index"
  resources :users, only: [:index, :show]   do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      get '/page/:page', action: :index, on: :collection
      resources :likes, only: [:create], path: ""
      resources :likes, only: [:destroy], path: ""
      resources :comments, only: [:create, :destroy], path: "comment"
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy, foreign_key: :post_id
  has_many :likes, dependent: :destroy, foreign_key: :post_id

  after_create :update_posts_counter
  after_destroy :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  paginates_per 3 # kaminari pagination

  def last_five_comments
    comments.order(created_at: :desc).limit(5).includes(:user)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  def index
    @posts = User.find(params[:user_id]).posts
    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :text))
    @post.author_id = current_user.id
    if @post.save
      flash[:success] = 'Post created successfully!'
      redirect_to user_posts_path
    else
      redirect_to request.referrer
      flash[:warning] = 'Post not created!'
    end
  end

  def show
    @post = Post.includes(:author, :likes, comments: [:user]).find_by_id(params[:id])
    @post_comments = @post.comments
    @post_like = @post.likes[0]
    @post_author = @post.author
    @post_comment_author = @post_comments.map(&:user).flatten
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:success] = 'Post deleted successfully!'
    else
      flash[:warning] = 'Post not deleted!'
    end
    redirect_to request.referrer
  end
end

app/views/posts/_post.html.erb
<div class="card mt-3 ms-3 me-3">
  <div class="card-body">
    <div class='d-flex justify-content-between'>
      <h5 class="card-title"><%= post.title %> #<%= i %></h5>
      <% if post.author_id == current_user.id || can?(:destroy, current_user) %>
        <%= button_to "Delete", user_post_path(post.author_id, post.id), method: :delete, class: "btn btn-outline-secondary" %>
      <% end %>
    </div>
    <%= link_to user_post_path(params[:id].to_i, post.id) do %>
      <p class="card-text"><%= post.text[0,100]+" ..." %></p>
      <p class="card-text text-end">
        <small class="text-body-secondary">
          Comments: <%= post.comments_counter %>,
          Likes: <%= post.likes_counter %>
        </small>
      </p>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= link_to user_path(params[:user_id]) do %>
  <%= render partial: "users/user", locals: { user: @user } %>
<% end %>
<ul>
  <% @posts.each_with_index do |post , i| %>
      <li>
          <%= render partial: "post", locals: { post: post, i: i } %>
          <% if post.comments_counter != 0 %>
            <%= render partial: "comments/comment", locals: { comments: post.last_five_comments } %>
          <% end %>
      </li>
  <% end %>
</ul>
<div class="text-center mb-4">
  <div class="d-flex justify-content-center p-2">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= link_to user_path(params[:user_id]) do %>
  <%= render partial: "users/user", locals: { user: User.find(params[:user_id]) } %>
<% end %>
<section class="m-3">
  <h1>New Post</h1>
  <%= form_with model: @post, url: "/users/#{params[:user_id]}/posts" do |form| %>
    <div>
      <%= form.label :title, hidden: true %><br>
      <%= form.text_field :title, placeholder: "Add Post Title", class: "btn border-secondary-subtle text-start mb-2"  %>
    </div>
      <%= form.label :text, hidden: true  %>
      <%= form.text_area :text, cols: 50, placeholder: "Add Post Text", class: "btn border-secondary-subtle text-start mb-3"  %>
    </div>
    <div>
      <%= form.submit "Post", class: "btn btn-outline-secondary" %>
    </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<%= link_to user_posts_path(@post_author.id) do %>
  <article class="card mt-3 ms-3 me-3">
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h5 class="card-title"><%= @post.title %> by <%= @post_author.name %></h5>
        <p class="card-text text-end">
          <small class="text-body-secondary">
            Comments: <%= @post.comments_counter %>,
            Likes: <%= @post.likes_counter %>
          </small>
        </p>
      </div>
      <p class="card-text"><%= @post.text %></p>
    </div>
  </article>
<% end %>

<section class="btn-container d-flex">
  <%= render partial: "likes/like", locals: { like: @post_like, user_id: @post_author.id, post_id: @post.id } %>
  <div class="mt-3">
    <button class="btn btn-outline-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Add a comment
    </button>
  </div>
</section>

<%= render partial: "comments/create"%>

<section class="show-comments">
  <% if @post_comments.present? %>
    <%= render partial: "comments/comment", locals: { comments: @post_comments, user: @post_comment_author } %>
  <% end %>
</section>